### ISSUE TITLE
Unable to pull variables in manual sync approach

### ISSUE THREAD

**Issue by neyara** [Infisical/infisical-cli#4]
Hey there,

I was following Infisical's doc and, at first, tried the auto sync approach in my NestJS project. Everything seemed to work fine (it asked for credentials and the project's ID), but the `.env.infisical` file content was just the project ID and no variables. 

So then I tried the manual approach where I emptied the env file and executed `npx infisical pull dev`, and as a result, I got the following message: `The "path" argument must be of type string. Received undefined`. This time no info about credentials or project ID was asked (maybe because I informed it in the previous step?). Also, the env file remained empty.

**Comment by dangtony98** [comment]
Hey neyara!

Sorry to hear about  the trouble ... So to clarify:

- The .env.infisical file should contain an ID to your project/workspace on Infisical; it won't be populated with your variables.
- You're right that in the previous step, once it's been informed then it won't ask you again for that information. The .env file should've been populated though, so that's strange.

We always recommend using Infisical with the automatic approach. In our case, since you're using NestJS, you'd want to modify your package.json file dev script to the following:

 ["start:dev": "npx infisical dev nest start --watch"](url)

Afterward, you should be able top run `"npm run start:dev"` to start up your development server.

Can you hop over to our Slack channel [here](https://infisical.slack.com/ssb/redirect)? — I'd be more than happy to assist you in real-time!

**Comment by neyara** [comment]
Oh, I didn't realize the .env.infisical was actually supposed to have the project ID... And I had deleted it before executing `npx infisical pull dev` since I mistakenly thought it was the "default" env file when using Infisical. I guess that would explain why I'm getting the "undefined" error now. Is there a way to regenerate this file (.env.infisical)? I tried recreating it manually, but the error still persists.

**Comment by dangtony98** [comment]
You should be able to modify your dev script as above with `"start:dev": "npx infisical dev nest start --watch"` and run `npm run start-dev` . It'll recognize that the .env.infisical file is missing and prompt you to input your workspace/project ID again!

**Comment by neyara** [comment]
Thanks, that worked! Even though the .env file was not filled visually, the project started with no complaints :sweat_smile:
I'll keep investigating, I may have missed something. But I appreciate your help :smile:

**Comment by dangtony98** [comment]
Yay! That's awesome — The automatic approach works like magic 🙂

We support .env files as well (you'd have to manually type `npx infisical pull dev` to update or reconstruct it locally) but the automatic approach is a lot better because you and your team can stay in sync with the right set of environment variables at all times hereon!
